name: bytes_io
description: a python-like bytes_io implementation for dart
version: 1.0.1
homepage: https://github.com/guo40020/bytes_io.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
